# Generated by Django 4.2.10 on 2024-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_profile_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification',
            field=models.CharField(max_length=9, unique=True, verbose_name='identification'),
        ),
    ]
