runserver: 
    #!/bin/bash
    
    transactions_count=$(python manage.py shell -c "from transaction.models import Commission; print(Commission.objects.count())")
    whitelistedbanks_count=$(python manage.py shell -c "from transaction.models import WhitelistedBank; print(WhitelistedBank.objects.count())")

    if [ "$transactions_count" -eq 0 ] || [ "$whitelistedbanks_count" -eq 0 ]; then
        python manage.py loadbanks
        python manage.py loadcomissions
    fi

    python manage.py runserver


migrate: 
    python manage.py migrate

makemigrations  app="":
    python manage.py makemigrations {{ app }} 

shell:
    python manage.py shell

check: 
    python manage.py check

dockup:
    docker compose up

clean:
    #!/usr/bin/env bash
    find . -name '__pycache__' -not -path "./.venv/*" -prune -exec rm -rf {} \;
    find . -name '*.pyc' -not -path "./.venv/*" -exec rm {} \;
    find . -name '.DS_Store' -not -path "./.venv/*" -exec rm {} \;
    rm -rf .mypy

loadbasics:
    python manage.py loadbanks && python manage.py loadcomissions

dockdown:
    docker compose down

zip: clean
    #!/usr/bin/env bash
    rm -f {{ project_name }}.zip
    zip -r {{ project_name }}.zip . -x .env .venv/* .git/*