runserver: 
    python manage.py runserver

migrate: 
    python manage.py migrate

makemigrations  app="":
    python manage.py makemigrations {{ app }} 

shell:
    python manage.py shell

check: 
    python manage.py check