# Generated by Django 4.2.7 on 2023-11-03 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('alias', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('BK', 'Blocked'), ('DS', 'Disabled')], default='AC', max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('alias', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('BK', 'Blocked'), ('DS', 'Disabled')], default='AC', max_length=2)),
                ('pin', models.CharField(max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='account.account')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='account_car_code_e2f867_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='account_acc_code_c327ff_idx'),
        ),
    ]
