# Generated by Django 4.2.7 on 2023-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
