# Generated by Django 4.2.7 on 2023-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_card_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
