# Generated by Django 4.2.7 on 2023-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_alias_alter_card_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='account_acc_code_c327ff_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('BLK', 'Blocked'), ('DIS', 'Disabled')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('BLK', 'Blocked'), ('DIS', 'Disabled')], default='ACT', max_length=3),
        ),
    ]
