# Generated by Django 4.2.7 on 2023-11-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_account_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="pin",
            field=models.CharField(max_length=255),
        ),
    ]
