# Generated by Django 4.2.7 on 2023-11-27 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_card_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2028, 11, 25, 2, 43, 1, 479413, tzinfo=datetime.timezone.utc)),
        ),
    ]
