# Generated by Django 4.2.7 on 2023-11-27 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_card_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2028, 11, 25, 11, 31, 46, 984553, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
