# Generated by Django 4.2.7 on 2023-11-27 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_card_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="cvv",
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="alias",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="card",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2028, 11, 25, 17, 36, 40, 16626, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="pin",
            field=models.CharField(max_length=3),
        ),
    ]
