# Generated by Django 4.2.7 on 2023-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_alter_card_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="expiry",
            field=models.DateTimeField(),
        ),
    ]
