# Generated by Django 4.2.7 on 2024-01-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_card_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, default='Adabank Account', max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(default='Adabank Card', max_length=250),
        ),
    ]
