# Generated by Django 4.2.7 on 2024-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_alias_alter_card_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(blank=True, default='Adabank Card', max_length=250),
        ),
    ]
