# Generated by Django 4.2.10 on 2024-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_balance_alter_card_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, default='Adabank Account', max_length=250, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=100, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('BLK', 'Blocked'), ('DIS', 'Disabled')], default='ACT', max_length=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(blank=True, default='Adabank Card', max_length=250, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry',
            field=models.DateTimeField(verbose_name='expiry'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(max_length=3, verbose_name='pin'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('BLK', 'Blocked'), ('DIS', 'Disabled')], default='ACT', max_length=3, verbose_name='status'),
        ),
    ]
