# Generated by Django 4.2.10 on 2024-02-20 00:33

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_account_alias_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, default=account.utils.get_random_name, max_length=250, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(blank=True, default=account.utils.get_random_name, max_length=250, verbose_name='alias'),
        ),
    ]
