# Generated by Django 4.2.7 on 2023-11-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('agent', models.CharField(max_length=200)),
                ('concept', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kind', models.CharField(choices=[('PY', 'Payment'), ('IC', 'Incoming'), ('OC', 'Outcoming')], max_length=2)),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='transaction_timesta_0d34d5_idx'), models.Index(fields=['target_ct', 'target_id'], name='transaction_target__20304e_idx')],
            },
        ),
    ]
