# Generated by Django 4.2.7 on 2023-11-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_alias_alter_card_code'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_target__20304e_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target_ct',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.card'),
        ),
    ]
