# Generated by Django 4.2.7 on 2023-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_transaction_target__20304e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('PAY', 'Payment'), ('INC', 'Incoming'), ('OUT', 'Outcoming')], max_length=3),
        ),
    ]
