# Generated by Django 4.2.7 on 2023-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTaxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAY', 'Payment'), ('INC', 'Incoming'), ('OUT', 'Outcoming')], max_length=3)),
                ('range1', models.PositiveIntegerField()),
                ('range2', models.PositiveIntegerField()),
                ('range3', models.PositiveIntegerField()),
            ],
        ),
    ]
