# Generated by Django 4.2.7 on 2023-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactiontaxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAY', 'Payment'), ('INC', 'Incoming'), ('OUT', 'Outcoming')], max_length=3)),
                ('range1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('range2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('range3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionTaxes',
        ),
    ]
