# Generated by Django 4.2.7 on 2023-11-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0005_commission_delete_transactiontaxes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhitelistedBanks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("url", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
