# Generated by Django 4.2.7 on 2023-11-11 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0006_whitelistedbanks_transaction_commission"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WhitelistedBanks",
            new_name="WhitelistedBank",
        ),
    ]
