# Generated by Django 4.2.7 on 2023-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0007_rename_whitelistedbanks_whitelistedbank"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelistedbank",
            name="code",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
