# Generated by Django 4.2.10 on 2024-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_transaction_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='kind',
            field=models.CharField(choices=[('PAY', 'Payment'), ('INC', 'Incoming'), ('OUT', 'Outcoming')], max_length=3, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='range1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='range 1'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='range2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='range 2'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='range3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='range 3'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='agent',
            field=models.CharField(max_length=200, verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='comission'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='concept',
            field=models.CharField(max_length=50, verbose_name='concept'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('PAY', 'Payment'), ('INC', 'Incoming'), ('OUT', 'Outcoming')], max_length=3, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='whitelistedbank',
            name='code',
            field=models.CharField(max_length=2, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='whitelistedbank',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
