# Generated by Django 4.2.10 on 2024-02-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_commission_kind_alter_commission_range1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='balance'),
            preserve_default=False,
        ),
    ]
